#!/usr/bin/env bash
#
# opus/mayhem/build.sh — build xiph/opus's decode fuzz harness (opus_decode_fuzzer) as a sanitized
# libFuzzer target (+ a standalone run-once reproducer).
#
# Fuzzed surface: libopus's core DECODER. The harness (tests/opus_decode_fuzzer.c, shipped upstream;
# we keep a verbatim copy under mayhem/harnesses/) treats the input as a stream of length-prefixed
# Opus packets, creates an OpusDecoder from the first packet's ToC, then drives opus_decode() over
# the packets (including simulated lost packets / FEC). Inputs are raw concatenated opus_demo-style
# packets, NOT Ogg containers.
#
# Build contract comes from the org base ENV: CC/CXX/SANITIZER_FLAGS/LIB_FUZZING_ENGINE/SRC/OUT/
# STANDALONE_FUZZ_MAIN. We build libopus ITSELF with $SANITIZER_FLAGS so the decoder code (not just
# the harness) is instrumented; -fsanitize=fuzzer-no-link adds coverage to the library; the
# libFuzzer runtime ($LIB_FUZZING_ENGINE) is linked only into the harness. Outputs land in $OUT.
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# `=` (not `:=`) for SANITIZER_FLAGS so an explicit empty --build-arg builds with NO sanitizers.
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
# DEBUG_FLAGS: explicit DWARF-3 so Mayhem's triage (DWARF < 4 required) can read symbols; clang-19
# defaults to DWARF-5 with plain -g. Overridable; threaded AFTER $SANITIZER_FLAGS in every compile.
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${SRC:=$(cd "$(dirname "$0")/.." && pwd)}"
: "${OUT:=/mayhem}"
: "${MAYHEM_JOBS:=$(nproc)}"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX LIB_FUZZING_ENGINE SRC OUT MAYHEM_JOBS

# Coverage instrumentation for the library so the fuzzer sees decoder edges. (The libFuzzer target
# also gets -fsanitize=fuzzer from $LIB_FUZZING_ENGINE; the standalone reproducer does not, so build
# the library with -fsanitize=fuzzer-no-link to keep both link forms working.)
COV="-fsanitize=fuzzer-no-link"

cd "$SRC"

HARNESS_DIR="$SRC/mayhem/harnesses"
mkdir -p "$OUT"

# ── 1) Build libopus from source WITH sanitizers (instrument the fuzzed decoder) ──────────────────
export CFLAGS="${CFLAGS:-} $SANITIZER_FLAGS $COV $DEBUG_FLAGS"
export CXXFLAGS="${CXXFLAGS:-} $SANITIZER_FLAGS $COV $DEBUG_FLAGS"

./autogen.sh
# --enable-assertions surfaces internal consistency checks; static-only keeps the link self-contained.
./configure --enable-static --disable-shared --disable-doc --disable-extra-programs \
            --enable-assertions
make -j"$MAYHEM_JOBS"

LIBOPUS="$SRC/.libs/libopus.a"
[ -f "$LIBOPUS" ] || { echo "ERROR: $LIBOPUS not built" >&2; exit 1; }

# config.h is generated by ./configure at the repo root; the harness includes it under HAVE_CONFIG_H.
INC="-DHAVE_CONFIG_H -I$SRC -I$SRC/include -I$SRC/celt -I$SRC/silk"

# ── 2) Build the harness twice: libFuzzer (-> $OUT/opus_decode_fuzzer) + standalone reproducer ────
harness=opus_decode_fuzzer

# libFuzzer target
$CC $SANITIZER_FLAGS $DEBUG_FLAGS $INC \
    "$HARNESS_DIR/$harness.c" $LIB_FUZZING_ENGINE \
    "$LIBOPUS" -lm \
    -o "$OUT/$harness"

# standalone reproducer (no libFuzzer runtime; reads one input file)
$CC $SANITIZER_FLAGS $DEBUG_FLAGS $COV $INC \
    "$HARNESS_DIR/$harness.c" "$HARNESS_DIR/${harness}_standalone.c" \
    "$LIBOPUS" -lm \
    -o "$OUT/$harness-standalone"

echo "built $harness (+ standalone)"
ls -la "$OUT/$harness" "$OUT/$harness-standalone" 2>&1 || true
